main-readcsv:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=gnu99 readcsv.c -o readcsv
run-readcsv:
	./readcsv
main-formatdate:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Werror -Wall -std=gnu99 format_date.c -o format_date
run-formatdate:
	./format_date