#!/bin/sh

test_env=false

while getopts 't' flag; do
    case "${flag}" in
        t)  test_env=true ;;
    esac
done

clear

dir=${PWD##*/}
if [ $dir = 'scripts' ]; then
    cd ..
fi

if [ $test_env = false ]; then
    make mem
else
    make all
fi

for testCasesDir in ./test-cases/*; do
    echo
    echo
    version="${testCasesDir##*/}"
    ./scripts/update-binaries -v "$version"

    for testCase in $testCasesDir/*.in; do
        current="$(echo "$testCase" | sed 's/\.\/test-cases\///')"
        output="$(echo "$testCase" | sed 's/\.in/.out/')"

        expected="$(cat $output)"
        received="$(./main < $testCase)"

        if [ "$expected" = "$received" ]; then
            echo "ok   - $current"
        else
            printf "\nERR! - %s\n\n" "$current"
            printf "EXPECTED OUTPUT:\n%s\n\n" "$expected"
            printf "RECEIVED OUTPUT:\n%s\n\n-----------\n\n" "$received"
        fi
    done
done

./scripts/update-binaries -v 03

