name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: make

  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: make test
    needs: build
